### ISSUE TITLE
Help from CatBoost team

### ISSUE THREAD

**Issue by sab** [conda-forge/r-catboost-feedstock#6]
Hi, @dbast!

I'm from CatBoost team. Could you add me (@sab) and/or Stanislav (@kizill) into maintainers list?
We could help to keep r-catboost-feedstock up-to-date and enhance build with GPU support.

Thanks,
Sergey

**Comment by dbast** [comment]
Hi @sab, hi @kizill

nice to see you guys here. Any help is very much appreciated.

You can directly contribute by forking the repo and provide changes via pull request. As part of such a change you can additionally add yourself to the recipe-maintainers in the meta.yaml. The repo permissions are automatically adjusted after a change is merged.

Some work is currently prepared in https://github.com/conda-forge/r-catboost-feedstock/pull/2 which looks like that the devtools package or its dependencies are broken on win-64 for R3.5. I am currently thinking to disable the win-64 build and enable it again after devtools are fixed.

Would GPU support come via this existing package or via a new package like r-catboost-gpu? If it is the later, new packages come through a PR to https://github.com/conda-forge/staged-recipes.

**Comment by dbast** [comment]
The devtools problems seem to be resolved by not using it anymore. New r-catboost packages are uploaed.

**Comment by sab** [comment]
Hi!

It's good to see that you replaced devtools solution with package upload from release page. Training on GPU should work now.

We'll make contribution (via pull request) next time :)

**Comment by msarahan** [comment]
That's actually possibly not good. Though it seems like less work on first
glance, packaging binaries from other sources instead of building from
source with our tools can introduce binary compatibility issues. I'm not
sure there's any way around it right now, since conda forge does not yet
have a good story for compiling with GPU support (that I know of, anyway).

Just keep in mind that this approach is a technical risk that may make your
package less compatible with the rest of the collection.

**Comment by dbast** [comment]
Well, this package was always created from the binaries from the catboost gh-release page. It was recently only re-rendered, updated to the newest binary version and updated to be created without devtools.

Why it is created like that from the beginning and what are the binary/lib/driver requirements for the GPU part to work, is a good question. Maybe @sab knows this / can help here.

**Comment by kizill** [comment]
We've taken the risk of possible binary incompatibility both in Python and R packages and in practice there should be no problems: for example, our R library exports only regular C functions and everything it needs is statically linked.

**Comment by msarahan** [comment]
You should be mostly fine, then. Which compiler do you use on Linux? What about on mac? Are you building against an old glibc on Linux? We try to be compatible back to centos 6 (glibc 2.12) on Linux. On mac, we try to be compatible back to 10.9.
